server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO

spring:
  profiles:
    #    active: myTests
    active: ${PROD:dev}

adminPassword: ${SECRET:$2a$10$DordpFcR24yGzOrOl1AKe.sVSYIAxp6ZpZ84MS5UlDcztxbjvcp8G}
adminName: KrylovaDi

jwt-token-secret: ${JWT-SECRET:lkrfslrekjfalecmasieuro3wurhnsjkcafjsefljashkfaewjkfljsrhkjgjsfndjtgtdlgjsghsjdyr}
# 3600000 - 1 hour
jwt-token-expired: 1800000

