server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO

spring:
  profiles:
    #    active: myTests
    active: ${prod:dev}
  mail:
    host: ${host:127.0.0.1}
    username: ${mail:user}
    password: ${mailpassword:password}
    port: ${mailport:3025}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

jwt-token-secret: ${JWT-SECRET:lkrfslrekjfalecmasieuro3wurhnsjkcafjsefljashkfaewjkfljsrhkjgjsfndjtgtdlgjsghsjdyr}
# 3600000 - 1 hour
jwt-token-expired: 3600000

email: $(email:123@123.com)

