spring:
#  datasource:
#    url: jdbc:h2:file:./src/main/resources/db/myDB/myDB
#    username: sa
#    password:

  datasource:
    url: jdbc:mysql://localhost:3306/my_db
#    driver: com.mysql.jdbc.Driver
    username: bestuser
    password: bestuser

  h2:
    console:
      enabled: true
      path: /h2console/
      settings:
        web-allow-others: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate