server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO

spring:
  profiles:
    #    active: myTests
    active: ${PROD:dev}

PASSWORD: ${SECRET:$2a$10$DordpFcR24yGzOrOl1AKe.sVSYIAxp6ZpZ84MS5UlDcztxbjvcp8G}

